# Site settings
title: 2PiHoops
email: ejdarrow@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  Because Hooping is Awesome
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://2pihoops.github.io" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
